### ISSUE TITLE
Highlight string interpolation

### ISSUE THREAD

**Issue by mlutze** [flix/vscode-flix#133] opened 2021-08-11 10:26 UTC

**Comment by magnus-madsen** [comment] 2021-08-11 13:47
I actually don't know if VSCode can support this out of the box.

**Comment by magnus-madsen** [comment] 2021-11-10 14:21
@mlutze @jhckragh How do we solve this:

![image](https://user-images.githubusercontent.com/2287953/141130101-c1274691-0a8b-406b-86d5-01267d57124d.png)
??

**Comment by magnus-madsen** [comment] 2021-11-10 14:22
Do we need to handle strings entirely in LSP or can something be done with the regex?

**Comment by magnus-madsen** [comment] 2021-11-10 15:15
Let's hear what @jhckragh says. If it can't be handled then I think we should remove strings from the grammar and then we deal with it in LSP.

**Comment by magnus-madsen** [comment] 2021-11-10 17:11
Would it be possible to only match strings that do not contain: any ${}? Then we can still do basic strings while dealing with the more complicated ones in LSP.

**Comment by jhckragh** [comment] 2021-11-10 17:25
Good question! I just tried out the following small example:

```
def main(_: Array[String]): Int32 & Impure =
    let r1 = {fstName = "Julius", lstName = "Caesar"};
    "Mr. ${r1.fstName} ${r1.lstName}" |> println;
    0
```

Here the Flix language server yields the following semantic tokens:

```
[0:4] 'main' (FUNCTION)
[0:9] '_: Array[String]' (PARAMETER)
[0:12] 'Array' (TYPE)
[0:18] 'String' (TYPE)
[0:28] 'Int32' (TYPE)
[1:8] 'r1' (VARIABLE)
[1:14] 'fstName' (PROPERTY)
[1:34] 'lstName' (PROPERTY)
[2:9] '${r1.fstName}' (METHOD)
[2:11] 'r1' (VARIABLE)
[2:14] 'fstName' (PROPERTY)
[2:23] '${r1.lstName}' (METHOD)
[2:25] 'r1' (VARIABLE)
[2:28] 'lstName' (PROPERTY)
[2:38] '|>' (OPERATOR)
[2:41] 'println' (PARAMETER)
```

So again the trouble here is token overlap. For example, these tokens overlap:

```
[2:9] '${r1.fstName}' (METHOD)
[2:11] 'r1' (VARIABLE)
[2:14] 'fstName' (PROPERTY)
```

Personally, I would recommend omitting "method" tokens for `${...}`. I think everything will work nicely if they're not sent. 🙂

Also @mlutze, you're of course right that a single regex cannot handle the arbitrary nesting that Flix allows. But the regex mechanism in VSCode is more powerful than that: You can specify an "opening" regex and a "closing" regex, and VSCode will handle nesting properly (I think). The builtin JS extension handles nesting, and I think it uses the grammar file to highlight `${` and `}`:

![js-str-nesting](https://user-images.githubusercontent.com/129259/141162392-47f558d8-3c93-46a4-aa8d-ca3a457c6d9b.png)

**Comment by jhckragh** [comment] 2021-11-10 19:51
Follow up: After looking at the grammar file for the builtin JS extension I can confirm that it uses the begin/end regex mechanism to handle string interpolation:

https://github.com/microsoft/vscode/blob/main/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json#L4760-L4780

Note also the `"include": "#expression"`: they actually use the grammar file to also highlight the inside content of `${...}`. In fact, their master grammar file is quite a thing to behold, featuring monster regexes like the following. 😁

https://github.com/microsoft/TypeScript-TmLanguage/blob/master/TypeScriptReact.tmLanguage#L643-L715

**Comment by magnus-madsen** [comment] 2021-11-10 19:51
I will try to remove the overlapping tokens and we can go from there.

**Comment by magnus-madsen** [comment] 2021-11-10 22:28
I think I fixed it in master.

**Comment by jhckragh** [comment] 2021-11-11 05:50
With the latest master the above example now looks right. 🙂

![0](https://user-images.githubusercontent.com/129259/141244248-fac4894e-f491-40be-a1cf-5142c1e9f708.png)

However, there seems to be some problems with nesting:

![1](https://user-images.githubusercontent.com/129259/141244445-b3d0f6d7-3859-46d5-94c1-aa579160f886.png)

I think the problem here is in the grammar file. We probably need to do something like the `"include": "#expression"` thing they have in the TypeScript grammar file. We don't need to capture every expression, but just need to allow the syntax highlighting to apply recursively to the contents of `"..."` and "${...}". I'm away most of the day, but I can look into it during the weekend.

**Comment by magnus-madsen** [comment] 2021-11-12 14:27
Solved in master!

**Closed by magnus-madsen** 2021-11-12 14:27 UTC
